### ISSUE TITLE
Mailchimp Subscription has Shachar's name

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-server#76]
@shachar-langer I couldn't figure out exactly why this is as the settings appear correct in Mailchimp and in Google Admin. We can try to debug tomorrow

![image](https://user-images.githubusercontent.com/6589960/103589562-a9d29a80-4eb9-11eb-9b8c-c1f21e42b2ca.png)

**Comment by shachar-langer** [comment]
Done
